AllCops:
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'db/**/*.rb'
    - 'vendor/**/*'
    - 'spec/**/*.rb'
    - 'bin/**/*'
  DisplayCopNames: true
Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
